### PR TITLE
Add harmony reflect polyfill

### PR DESCRIPTION
**Pull request by okcoker**
To alleviate #5 for now.

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
:-1: 
as I said [here](https://github.com/andreypopp/autobind-decorator/issues/2#issuecomment-99630763) all target browsers could have native Symbol / Polyfill. we should just add some notes about one might be should use polyfills to use autobind decorator. we need babel to use this anyway. so it's possible that user of this decorator already uses core.js (or even harmony-reflect or other polyfill). also this dependancy should be definitely added to peerDependencies if it will be added though

**Comment by andreypopp** [comment]
Native support for Reflect is almost not existent at the moment. Not sure if we want to require it explicitly though...

**Comment by aldendaniels** [comment]
:-1: 

What about progressive enhancement?
 1. If Reflect is globally defined, then use it.
 2. If not, then use `getOwnPropertyNames` and don't worry about symbols

**Comment by andreypopp** [comment]
@aldendaniels good suggestion, anybody wants to submit a PR?

**Comment by domarmstrong** [comment]
Created PR #8

**Pull request closed without merging**
