### PR TITLE
autobind classes and methods

### PR DESCRIPTION
**Pull request by dominataa**
Hi. I was working on this myself in an experimental project so thought id contribute it as I came across your repo which you've already published.

### CODE REVIEW

**Comment by andreypopp** [comment]
That's pretty cool, thanks! Are you ok if I add you as a collaborator to the repo and on npm?

**Comment by dominataa** [comment]
That would be good thanks

**Comment by andreypopp** [comment]
Added on github, what's you npm username?

**Comment by dominataa** [comment]
`domarmstrong`

**Comment by andreypopp** [comment]
OK, added there too.

**Pull request merged**
