### PR TITLE
fix(core): allow user assign new method

### PR DESCRIPTION
**Pull request by acrazing**

### CODE REVIEW

**Comment by stevemao** [comment]
What about https://github.com/andreypopp/autobind-decorator/pull/29? @acrazing

**Comment by acrazing** [comment]
This method of #29 is not reusable if user set a new value to the field.

**Comment by stevemao** [comment]
@acrazing I'm not sure if I understand you. Could you add some tests?

**Comment by pablo-coco** [comment]
Guys, can this be merged/or add tests so it can be merged?

**Comment by stevemao** [comment]
@pablo-coco see my comments

**Comment by acrazing** [comment]
Will, I created a new pull request #58 to add test code and fix bugs, because I deleted the old repo.

**Please note that the new decorator bind setter/getter to the field, may cause some performance loss.**

**Pull request closed without merging**
