### PR TITLE
change some variables declarations to const instead of let

### PR DESCRIPTION
**Pull request by chicoxyzzy**
so js engines of future will be able to improve performance

### CODE REVIEW

**Comment by sebmck** [comment]
Not going to argue about code style but constants are just as optimisable as any other variables :)

**Comment by chicoxyzzy** [comment]
hm... I thought js engines can optimize code better with `const`'s. anyway it's more bulletproof because of immutability :)

**Comment by sebmck** [comment]
You can infer just as much information from any variable declaration that's
not reassigned.

On Thursday, 7 May 2015, Sergey R <notifications@github.com> wrote:

> hm... I thought js engines can optimize code better with const's. anyway
> it's more bulletproof because of immutability :)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/andreypopp/autobind-decorator/pull/4#issuecomment-99650716>
> .
>


-- 
Sebastian McKenzie

**Comment by andreypopp** [comment]
I don't like how `const` looks vs `let` :-)

**Comment by chicoxyzzy** [comment]
ok no problem :)

**Pull request closed without merging**
