### PR TITLE
Fix typescript declaration

### LINKED ISSUE #51: 1.4.1? export = autobind breaks our builds
Please have a look as fast as possible. We have downgraded to 1.4.0

============================================
Showing  1 changed file  with 1 addition and 1 deletion.
View  
2  index.d.ts
@@ -1,4 +1,4 @@
  declare module 'autobind-decorator' {
    const autobind: ClassDecorator & MethodDecorator;
 -  export default autobind;
 +  export = autobind;
  }
============================================

### PR DESCRIPTION
**Pull request by MNBuyskih**
Valid typescript declaration and close #51

### CODE REVIEW

**Comment by stevemao** [comment]
CC @blaremc @tscholl2

**Comment by tscholl2** [comment]
I also don't use this library anymore,  I also follow this pattern: https://github.com/andreypopp/autobind-decorator/issues/35#issuecomment-248278376

But I tried the PR and everything compiled so looks good to me.

**Comment by shutnickwork** [comment]
I need this! Aprove please!

**Comment by yanel777** [comment]
I need this too! Aprove please!

**Pull request merged**
